# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  #push:
    #branches: [ "master" ]
  pull_request:
    types:
      - opened
    branches: [ "master" ]
  pull_request_target:
    branches: [ "master" ]
    types:
      - closed
    
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: goaaroregistry.azurecr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME1: permit-api
  IMAGE_NAME2: permit-fe
  APP: testpermit-microservices
  APP1: TestPermitMicroAPI
  APP2: TestPermitMicroFrontEnd
  GIT_DEPLOY_REPO: moves-dlh-deploy-artifacts-ghactions
  GH_TOKEN: ${{ github.token }}

  eOPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  eOPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: "dlh-dev"

jobs:
  fetch:
    name: Code checkout and Sonar code scan
    #if: github.event_name == 'pull_request'
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'dev')
 
    runs-on: ubuntu-latest
    environment: 
      name: Dev
    steps:
    - name: Checkout git repository
      id: checkout
      uses: actions/checkout@v3


    - name: Analyze with SonarQube

        # You can pin the exact commit or the version.
        # uses: SonarSource/sonarqube-scan-action@v1.1.0
      uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on SonarQube, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)          
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}   # add the URL of your instance to the secrets of this repo with the name SONAR_HOST_URL (Settings > Secrets > Actions > add new repository secret)
      with:
          # Additional arguments for the sonarcloud scanner
        args:
            # Unique key of your project. You can find it in SonarQube > [my project] > Project Information (top-right menu)
            # mandatory
            -Dsonar.projectKey=MOVESTestPermitMicroServices
            # Comma-separated paths to directories containing main source files.
            #-Dsonar.sources= # optional, default is project base directory
            # When you need the analysis to take place in a directory other than the one from which it was launched
            #-Dsonar.projectBaseDir= # optional, default is .
            # Comma-separated paths to directories containing test source files.
            #-Dsonar.tests= # optional. For more info about Code Coverage, please refer to https://docs.sonarcloud.io/enriching/test-coverage/overview/
            # Adds more detail to both client and server-side analysis logs, activating DEBUG mode for the scanner, and adding client-side environment variables and system properties to the server-side log of analysis report processing.
            #-Dsonar.verbose= # optional, default is false

  build:
    name: Build code
    #if: github.event_name == 'pull_request'
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'dev')
    needs: [fetch]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout git repository
      id: checkout1
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: current directory path
      run: pwd
    - name: list current directory structure
      run: ls -lrt ./${{ env.APP1 }}/bin/Debug/net6.0
    - name: provide directory permissions
      run: echo $GITHUB_SHA

    - name: Upload built artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-dll
        path: ${{ env.APP1 }}/bin/Debug/net6.0/${{ env.APP1 }}.dll

  create-image:
    name: Create Image, scan & push to ACR
    #if: github.event_name == 'pull_request'
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'dev')
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Download built artifact
      uses: actions/download-artifact@v2
      with:
        name: app-dll
        path: ${{ env.APP1 }}/bin/Debug/net6.0/${{ env.APP1 }}.dll
        
   # - name: Build the Docker image
   #   run: docker build . --file ./${{ env.APP1 }}/Dockerfile --tag ${{ env.REGISTRY }}/024087d6-4aa7-4a52-90ec-0db8ffe1249e/dlh-dev/${{ env.IMAGE_NAME1 }}:$GITHUB_SHA
    - name: Build the Docker image
      run: docker build . --file ./${{ env.APP1 }}/Dockerfile --tag my-image-name:latest

    - name: Tag the Docker image with ACR tag/label
      run: docker tag my-image-name:latest ${{ env.REGISTRY }}/024087d6-4aa7-4a52-90ec-0db8ffe1249e/dlh-dev/${{ env.IMAGE_NAME1 }}:$GITHUB_SHA
 
    - name: Login to ACR
      run: docker login ${{ env.REGISTRY }} -u ${{ secrets.ACR_USR }} -p ${{ secrets.ACR_PWD }}
    - name: push to ACR
      run: docker push ${{ env.REGISTRY }}/024087d6-4aa7-4a52-90ec-0db8ffe1249e/dlh-dev/${{ env.IMAGE_NAME1 }}:$GITHUB_SHA

  scan-image:
    name: Scan container image
    #if: github.event_name == 'pull_request'
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'dev')
    needs: [create-image]
    runs-on: ubuntu-latest

    steps:
    - name: Login to ACR
      run: docker login ${{ env.REGISTRY }} -u ${{ secrets.ACR_USR }} -p ${{ secrets.ACR_PWD }}
    - name: Anchore grype scan download
      uses: anchore/scan-action/download-grype@v3
      id: grype
    - name: Anchore scan run
      id: grype-scan
      run: ${{steps.grype.outputs.cmd}} ${{ env.REGISTRY }}/024087d6-4aa7-4a52-90ec-0db8ffe1249e/dlh-dev/${{ env.IMAGE_NAME1 }}:$GITHUB_SHA -o json > scan-image-json.json
    - name: New Inspect grype scan json report
      run: cat scan-image-json.json
 
 
  kustomize:
    name: Update manifests with digest
    #if: github.event_name == 'pull_request'
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'dev')
    needs: [scan-image]
    runs-on: ubuntu-latest

    steps:
 
    - name: Clone deployment manifests repo
      run: |
          


          git config --global user.name "vishwanath-r-puranik"

          git config --global user.email "vishwanath.r.puranik@gov.ab.ca"

          git clone  https://vishwanath-r-puranik:${{ secrets.G_TOKEN }}@github.com/vishwanath-r-puranik/${{ env.GIT_DEPLOY_REPO }}.git 

    - name: list gitops folder structure
      run: ls -lrt ./${{ env.GIT_DEPLOY_REPO }}

    - name: 'Update patch with github commit Sha'
      run: |
          echo $GITHUB_SHA
          cp ./${{ env.GIT_DEPLOY_REPO }}/dev/patch-api-template.yaml ./${{ env.GIT_DEPLOY_REPO }}/dev/patch-api.yaml
          sed -i "s|:latest|:$GITHUB_SHA|g" ./${{ env.GIT_DEPLOY_REPO }}/dev/patch-api.yaml
        
          cat ./${{ env.GIT_DEPLOY_REPO }}/dev/patch-api.yaml

          cp ./${{ env.GIT_DEPLOY_REPO }}/dev/patch-fe-template.yaml ./${{ env.GIT_DEPLOY_REPO }}/dev/patch-fe.yaml
          sed -i "s|:latest|:$GITHUB_SHA|g" ./${{ env.GIT_DEPLOY_REPO }}/dev/patch-fe.yaml
          cat ./${{ env.GIT_DEPLOY_REPO }}/dev/patch-fe.yaml
          cd ./${{ env.GIT_DEPLOY_REPO }}
      

    - name: 'Kustomize deployment manifests and other artifacts'
      run: |
          oc kustomize ./${{ env.GIT_DEPLOY_REPO }}/dev > ./${{ env.GIT_DEPLOY_REPO }}/dev/deploy/${{env.APP}}.yaml

    - name: 'Upload updated deployment manifests'
      run: |
      
          cd ./${{ env.GIT_DEPLOY_REPO }}
          git add .

          git commit -m "committed from gh task"

          #git branch dev
          #git checkout dev
          #git push --set-upstream origin dev
          git push

  DeploytoDev:
    name: Deploy to Dev
    #if: github.event_name == 'pull_request'
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'dev')
    needs: [kustomize]
    runs-on: ubuntu-latest

    steps:
    - name: Clone updated deployment manifests repo
      run: |
          


          git config --global user.name "vishwanath-r-puranik"

          git config --global user.email "vishwanath.r.puranik@gov.ab.ca"

          git clone  https://vishwanath-r-puranik:${{ secrets.G_TOKEN }}@github.com/vishwanath-r-puranik/${{ env.GIT_DEPLOY_REPO }}.git 

    - name: Install OpenShift client
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: 4
    - name: Log in to OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.eOPENSHIFT_SERVER }}
        openshift_token: ${{ env.eOPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}

    - name: Deploy application onto Development OpenShift cluster environment
      run: |

         # oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER }}
          oc apply -f ./${{ env.GIT_DEPLOY_REPO }}/dev/deploy/${{env.APP}}.yaml
          
     # - name: Open Pull Request for Test deployment
     # run: |
     #     gh pr create --base master --head test --title "test-pr" --body "test-pr"
     #     
     # uses: devops-infra/action-pull-request@v0.5.3
     # with:
     #   github_token: ${{ secrets.GITHUB_TOKEN }}
     #   source_branch: test
     #   target_branch: master
     #   title: test pull request
     #   template: ''
     #   body: "**Automated pull request**"
     #   reviewer: vishwanath-r-puranik
     #   assignee: vishwanath-r-puranik
     #  label: enhancement
     #   milestone: My milestone
     #   draft: true
     #   old_string: "<!-- Add your description here -->"
     #   new_string: "** Automatic pull request**"
     #   get_diff: true
     #   ignore_users: "dependabot"
     #   allow_no_diff: true



  DeployToTest:
    name: Deployment to Test environment
    if: startsWith(github.head_ref, 'dev') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: 
      name: Test
    steps:
    - name: GitOps git repo clone
      run: |
          


          git config --global user.name "vishwanath-r-puranik"

          git config --global user.email "vishwanath.r.puranik@gov.ab.ca"

          git clone https://vishwanath-r-puranik:${{ secrets.G_TOKEN }}@github.com/vishwanath-r-puranik/${{ env.GIT_DEPLOY_REPO }}.git 

    - name: 'Update test deployment manifests'
      run: |
          echo $GITHUB_SHA
 
          cp ./${{ env.GIT_DEPLOY_REPO }}/dev/deploy/${{env.APP}}.yaml ./${{ env.GIT_DEPLOY_REPO }}/test/deploy/${{env.APP}}.yaml

    - name: 'Upload updated deployment manifests'
      run: |
      
          cd ./${{ env.GIT_DEPLOY_REPO }}
          git add .

          git commit -m "committed from gh task"
          git push
         # git branch test
          #git checkout test
         # git push --set-upstream origin test
           
        
         # git request-pull test https://github.com/vishwanath-r-puranik/moves-dlh-deploy-artifacts-ghactions master:test
    

    - name: Log in to OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.eOPENSHIFT_SERVER }}
        openshift_token: ${{ env.eOPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
        
    - name: Deploy application onto Test OpenShift cluster environment
      run: |

         # oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER }}
          oc apply -f ./${{ env.GIT_DEPLOY_REPO }}/test/deploy/${{env.APP}}.yaml
